# Site
repository: mrufflesmcghie/resume
# favicon: images/favicon.ico

# Personal info
name: Matt Ruffles-Mcghie
email: matt.rufflesmcghie@gmail.com
website: www.github.com/mrufflesmcghie/resume

darkmode: true

collections_dir: sections

collections:

  education:

    output: true

  projects:

    output: true

defaults:

  - scope: 

    type: education

    values:
     layout: education
     

      

# Social links
#twitter_username: 
github_username:  mrufflesmcghie
# dribbble_username: jekyll
facebook_username: matt.ruffles
# flickr_username: jekyll
instagram_username: rufflesmcghie1990
linkedin_username: matt-ruffles-mcghie-31525680
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile2.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Matt and I'm a <mark>Full Time Father</mark> & <mark>IT Support Engineer</mark> 

  After having 5 years away from <mark>IT</mark> to focus on <mark>Family Life</mark> I have made the decision to retrain in <mark>Teaching & Support Work in Schools.</mark>

  I am currently studying City & Guilds Level 2 Certificate in <mark>Supporting Teaching and Learning in Schools.</mark>
  
  In my spare time I'm also learning <mark>Full Stack Web Development </mark> primarily focusing on <mark>Laravel & Vue.</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: mrufflesmcghie/modern-resume-theme


sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
